# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='username',
        ),
    ]
