# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171205_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='所调查问卷班级'),
        ),
    ]
