# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171205_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='naire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tp',
            field=models.IntegerField(choices=[(1, '打分'), (2, '单选'), (3, 'c')]),
        ),
    ]
