# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171206_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='count_answer',
            field=models.IntegerField(default=0, verbose_name='统计回答问卷的学生数'),
        ),
    ]
